import feedparser
import os
from datetime import datetime, timedelta
from openai import OpenAI
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

# -------------------
# CONFIG
# -------------------
RSS_FEEDS = [
    "https://www.packagingdigest.com/rss.xml",
    "https://www.packagingeurope.com/rss",
    "https://www.sustainablebrands.com/rss.xml"
]

DAYS_BACK = 7

# -------------------
# FETCH ARTICLES
# -------------------
def fetch_articles():
    cutoff = datetime.utcnow() - timedelta(days=DAYS_BACK)
    articles = []

    for feed_url in RSS_FEEDS:
        feed = feedparser.parse(feed_url)
        for entry in feed.entries:
            if hasattr(entry, "published_parsed"):
                published = datetime(*entry.published_parsed[:6])
                if published > cutoff:
                    articles.append({
                        "title": entry.title,
                        "link": entry.link,
                        "summary": entry.get("summary", "")
                    })
    return articles

# -------------------
# AI SUMMARY
# -------------------
def summarize(articles):
    client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

    article_text = "\n\n".join(
        f"Title: {a['title']}\nSummary: {a['summary']}\nLink: {a['link']}"
        for a in articles
    )

    prompt = f"""
You are writing a weekly professional newsletter on sustainable packaging.

From the articles below, produce:
- 6–10 bullet points
- Each bullet must include:
  - Bold headline
  - 1–2 sentence summary
  - Source link

Focus on:
- Market trends
- Material innovation
- Corporate initiatives
- Policy or regulation

Articles:
{article_text}
"""

    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content

# -------------------
# EMAIL
# -------------------
def send_email(content):
    message = Mail(
        from_email=os.environ["FROM_EMAIL"],
        to_emails=os.environ["TO_EMAIL"],
        subject="🌱 Weekly Sustainable Packaging Report",
        html_content=f"""
        <h2>🌱 Weekly Sustainable Packaging Report</h2>
        <p><em>Week of {datetime.utcnow().strftime('%B %d, %Y')}</em></p>
        <div>{content}</div>
        <hr>
        <p style="font-size:12px;color:#666;">
        Automated weekly report generated by AI.
        </p>
        """
    )

    sg = SendGridAPIClient(os.environ["SENDGRID_API_KEY"])
    sg.send(message)

# -------------------
# MAIN
# -------------------
if __name__ == "__main__":
    articles = fetch_articles()

    if not articles:
        print("No articles found this week.")
        exit()

    summary = summarize(articles)
    send_email(summary)
    print("Weekly newsletter sent!")
